Uisp suspend
LibreQoE/LibreQoS pull request #360
Opened 2023-05-21 04:48 UTC by bile0026

Add ability to shape clients down to a specified upload and download speed when account is not in an "active" state. Cleaned up a bunch of formatting and convered comments to docstrings to help with automated documentation down the road.

To do:
[] Unit testing

Wanted to get this open for comment.

2023-05-22 21:17 UTC, rchac requested changes
Everything looks good except lines 212 and 220 of LibreQoS.py. With those changed back to ```if a < 1:``` we should be set.

2023-05-22 21:17 UTC, rchac commented on src/LibreQoS.py
> +				if a < 0:
Please set this as ```if a < 1:``` because HTB will not allow a rate of 0M

2023-05-22 21:17 UTC, rchac commented on src/LibreQoS.py
> +				if a < 0:
Please set this as ```if a < 1:``` because HTB will not allow a rate of 0M

2023-06-14 21:43 UTC, rchac commented
Hey sorry for the delay. I thought this over and had two concerns:

1) The PR doesn't have a toggle for this suspension option. In our case, I can see the default suspension option being a problem for our network. We do suspension by other means (a NAT redirect to a UISP suspension page) which runs on a different schedule. So if a client resumes service after being suspended, their first use of the service will often be limited to 2/2 Mbps or the chosen suspension speed for a while until the LibreQoS refresh takes effect. A customer who resumed billing will see very poor performance as their first impression for a few minutes, which could be bad. Perhaps this should be an optional feature that can be toggled with a variable in ispConfig.py?

2) I'm not certain that LibreQoS should handle the suspension in this way by limiting bandwidth. I think customers would just think things are slow rather than suspended. Requesting feedback though @thebracket @bile0026

2023-06-14 22:16 UTC, bile0026 commented
> Hey sorry for the delay. I thought this over and had two concerns:
> 
> 1. The PR doesn't have a toggle for this suspension option. In our case, I can see the default suspension option being a problem for our network. We do suspension by other means (a NAT redirect to a UISP suspension page) which runs on a different schedule. So if a client resumes service after being suspended, their first use of the service will often be limited to 2/2 Mbps or the chosen suspension speed for a while until the LibreQoS refresh takes effect. A customer who resumed billing will see very poor performance as their first impression for a few minutes, which could be bad. Perhaps this should be an optional feature that can be toggled with a variable in ispConfig.py?
> 2. I'm not certain that LibreQoS should handle the suspension in this way by limiting bandwidth. I think customers would just think things are slow rather than suspended. Requesting feedback though @thebracket @bile0026

For #1, I agree. I thought I had included that but I see that I did not. I will get that worked out and included.

As far as #2, at least in the case of UISP, the customer should get an email from UISP that their service has been suspended. This is similar to how Preseem handles suspension and has worked well for me in other environments. That said, I'm open to other ideas. I suppose it might be fairly trivial to have LibreQoS host a basic service suspension page or something like that. Personally I generally prefer a more all-in-one solution, vs having to stand up some other system to handle this via NAT or other redirect. So if there's a way to do the redirect within LibreQoS itself that would be slick.

2025-05-02 20:32 UTC, rchac commented
Feature already implemented

2025-05-02 20:32 UTC, closed without merging