improvement: add rustup command check and install it if its required
LibreQoE/LibreQoS pull request #502
Opened 2024-06-27 10:35 UTC by interduo

2024-06-27 21:26 UTC, thebracket commented
As I mentioned in the Zulip chat, I'm not approving anything that includes `apt install rustup`. That's a really busted way to install the Rust toolchain. Noticing that its not present, and directing the user to `rustup.rs` is fine - but not breaking the ability to ever update Rust properly again.

2024-06-27 21:29 UTC, thebracket commented
The error you list shows that `cargo` wasn't installed. The real rustup installs that for you. It's an even worse idea to do `apt install cargo`, because Cargo is designed to be updated by `rustup`.

2024-06-27 21:43 UTC, thebracket requested changes
The consistency change for `apt` is great. I like that.

Please replace:

```bash
if ! rustup -v &> /dev/null
then
    echo "rustup is not installed."
    echo "Let's try to install it"
    sudo apt install rustup
else
    echo "rustup found."
fi
```

```bash
if ! rustup -v &> /dev/null
then
    echo "rustup is not installed."
    echo "Visit https://rustup.rs and install Rust from there"
    echo "Usually, you can copy the following and follow the on-screen instructions."
    echo "Please don't install Rust as root."
    echo "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
else
    echo "rustup found."
fi
```

2024-06-28 13:19 UTC, thebracket approved these changes
Looks good to me.

2024-06-28 13:23 UTC, interduo commented
So merge it ;)

2024-06-28 13:23 UTC, thebracket commented
I will in a moment. Merging before coffee is dangerous...

2024-06-28 13:26 UTC, merged

2024-06-28 13:29 UTC, interduo commented
> I will in a moment. Merging before coffee is dangerous...

Best wishes from texas bar.

2024-06-28 13:30 UTC, thebracket commented
It's merged. :-)